service: nest-serverless

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs20.x

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline